export const HOME = "/";
export const LOGIN = "/login";
export const SIGN_UP = "/signup";
export const PROFILE = "/profile/:username";
export const NOT_FOUND = "/not-found";
export const UNIVERSAL = "/universal";
// export const CHAT = "/chat";
export const CHATWITH = '/chat/:friend';
export const IMAGEPAGE = '/image/:id';
